# Generated by Django 5.2.5 on 2025-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte')], default='telegram', max_length=50, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='bot',
            name='token',
            field=models.CharField(blank=True, help_text='API токен для подключения к мессенджеру', max_length=255, verbose_name='Токен бота'),
        ),
    ]
