# Generated by Django 5.2.5 on 2025-08-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_telegramuser_remove_bot_platform_remove_bot_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(help_text='Уникальный идентификатор сценария', max_length=100, unique=True, verbose_name='ID сценария')),
                ('name', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание сценария')),
                ('scenario_data', models.JSONField(help_text='JSON структура сценария с состояниями и переходами', verbose_name='Данные сценария')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserScenarioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(max_length=100, verbose_name='Текущее состояние')),
                ('context_data', models.JSONField(default=dict, help_text='Данные для передачи между состояниями', verbose_name='Контекстные данные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sessions', to='bots.bot', verbose_name='Бот')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='bots.scenario', verbose_name='Сценарий')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sessions', to='bots.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия сценария',
                'verbose_name_plural': 'Сессии сценариев',
                'ordering': ['-last_activity'],
                'unique_together': {('bot', 'telegram_user')},
            },
        ),
    ]
