# Generated by Django 5.2.5 on 2025-08-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_scenario_userscenariosession'),
        ('scenarios', '0003_alter_step_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscenariosession',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='scenarios.scenario', verbose_name='Сценарий'),
        ),
        migrations.RemoveField(
            model_name='userscenariosession',
            name='current_state',
        ),
        migrations.AddField(
            model_name='userscenariosession',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.step', verbose_name='Текущий шаг'),
        ),
        migrations.AlterField(
            model_name='userscenariosession',
            name='context_data',
            field=models.JSONField(default=dict, help_text='Данные для передачи между шагами', verbose_name='Контекстные данные'),
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
