version: '3.8'

services:
  db:
    image: postgres:15
    environment:
    POSTGRES_DB: apibot_db
      POSTGRES_USER: apibot_user
      POSTGRES_PASSWORD: your_strong_password_here
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - app-network
  restart: unless-stopped
    
  web:
    build: .
  depends_on:
    - db
  environment:
    DEBUG: "False"
    DATABASE_URL: postgresql://apibot_user:your_strong_password_here@db:5432/apibot_db
    SECRET_KEY: your_secret_key_here
  volumes:
    - static_volume:/app/staticfiles
    - media_volume:/app/media
  networks:
    - app-network
  restart: unless-stopped
    
  nginx:
    image: nginx:alpine
  depends_on:
    - web
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - static_volume:/app/staticfiles
    - media_volume:/app/media
  networks:
    - app-network
  restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge