# Generated by Django 5.2.5 on 2025-08-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data', models.JSONField(default=dict, verbose_name='Данные сценария')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шага')),
                ('step_type', models.CharField(max_length=50, verbose_name='Тип шага')),
                ('data', models.JSONField(default=dict, verbose_name='Данные шага')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scenarios.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Шаг сценария',
                'verbose_name_plural': 'Шаги сценариев',
                'ordering': ['scenario', 'order'],
                'unique_together': {('scenario', 'order')},
            },
        ),
    ]
