# Generated by Django 5.2.5 on 2025-08-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_scenario_userscenariosession'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Бот, к которому привязан сценарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bots.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('message', 'Сообщение'), ('input', 'Ввод данных'), ('condition', 'Условие'), ('action', 'Действие'), ('keyboard', 'Клавиатура'), ('delay', 'Задержка'), ('api_call', 'API вызов'), ('jump', 'Переход'), ('end', 'Завершение')], max_length=50, verbose_name='Тип шага'),
        ),
    ]
