# Generated by Django 5.2.5 on 2025-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_scenario_bot_alter_step_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('message', 'Сообщение'), ('input', 'Ввод данных'), ('condition', 'Условие'), ('action', 'Действие'), ('keyboard', 'Клавиатура'), ('delay', 'Задержка'), ('api_call', 'API вызов'), ('jump', 'Переход'), ('end', 'Завершение'), ('gpt_request', 'Запрос к GPT')], max_length=50, verbose_name='Тип шага'),
        ),
    ]
